repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 24.4.2 # Use the latest stable version of Black
    hooks:
    -   id: black
        args: [--line-length=110] # Or let it use pyproject.toml
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2 # Use the latest stable version
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-length", "110"] # Or let it use pyproject.toml
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0 # Use the latest stable version
    hooks:
    -   id: flake8
        args: [--max-line-length=110, --extend-ignore=E203,W503] # Or let it use pyproject.toml
        # additional_dependencies: [flake8-bugbear] # Example of adding flake8 plugins